name: Documentation Generator

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
          
      - name: List Repository Files
        run: ls -R

      - name: Show Current Directory
        run: pwd
